sudo: required
services:
  - docker

before_install:
  - docker build -t kowalewskik/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kowalewskik/docker-react npm run test -- --coverage
